version: '3.8'
name: cdn-app

services:
    frontend:
        image: bracketed/swiftcdn:development
        container_name: cdn-frontend
        restart: always
        depends_on:
            - backend
        networks:
            - cdn-network
        ports:
            - 3000:3000
        environment:
            EXPRESS_PORT: 3000
            COUCHDB_PORT: 5984
            UPLOAD_LIMIT: 1000 # In Megabytes
            BACKEND_USERNAME: admin
            BACKEND_PASSWORD: cdn

    backend:
        image: bracketed/couchdb:latest
        container_name: cdn-backend
        restart: always
        networks:
            - cdn-network
        ports:
            - 5984:5984
        volumes:
            - cdn-storage:/bitnami/couchdb
        environment:
            COUCHDB_PORT_NUMBER: 5984
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: cdn

networks:
    cdn-network:
volumes:
    cdn-storage:
